[package]
name = "dd_statechart"
version = "0.1.9"
authors = ["CJ McAllister <cjm571@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.14"
uuid = { version = "0.8", features = ["v4"] }
